### ISSUE TITLE
Create an Armada Dockerfile for development

### ISSUE THREAD

**Issue by Sharpz7** [G-Research/armada#1599] opened 2022-10-07 18:28 UTC
### The Idea

Create a Dockerfile that installs all the tools, programs and scripts that are needed to run armada. This would create a container that can be [ssh'd in to](https://phoenixnap.com/kb/how-to-ssh-into-docker-container) and then create a reliable enviroment that always behaves the same.

Upgrades would be as simple as downloading the new Dockerfile. Scripts would get signifcantly simpler since you wouldn't need code for edgecases of different enviroments. 

### Documentaition advantage
Since every part of the setup will be present in the repo in some way, we can document it part by part, explaining each element. 

### Next Steps

Or, taking it a step further you could install a instance of [remote vscode](https://github.com/coder/code-server) into the Dockerfile, and then set those up so people are able to deploy their own enviroment from the click of a button. 

Looking even further forward, this could be standardised using [coder](https://github.com/coder/coder), allowing teams to deploy armada dev instances on the fly with CPU and RAM requirements of your choosing.

### Progress so Far

In terms of progress, I have gotten as far as getting vscode working remotely (in my own time), and running the armada-server commands. I had failed to get clients to connect, but this can likely be fixed with some smarter docker config.

**Comment by Sharpz7** [comment] 2022-10-07 18:35
@kannon92 yeah, I'd say this is maybe an extention of that as we would also be supporting out own methods of install (i.e docker-compose)

**Comment by dave-gantenbein** [comment] 2022-10-18 12:45
Should we scope this down to just the vscode bit? I think there's another ticket for that somewhere, but it feels tantalizingly close to reality.

**Comment by dave-gantenbein** [comment] 2022-10-31 17:06
Look like this is largely a duplicate of other efforts.

**Closed by dave-gantenbein** 2022-10-31 17:06 UTC
